version: "3.9"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: tp-crawler-kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka